# An array of Sequences (19p)

## Overview of built-in sequences

*Container sequences* hold references to the objects they contain, which may be of any type, <br>
ex) list, tuple and collections.deque can hold items of different types <br>
while *flat sequences* physically store the value of each item within its own memory space, and not as distinct objects. <br>
ex) str, bytes, bytearray, memoryview and array.array hold items of one type.

Another way of grouping sequence types is by mutability <br>
Mutable sequences: list, bytearray, array.array, collections.deque and memoryview<br>
Immutable sequences: tuple, str and bytes

### List comprehensions and readability

In [1]:
#for loop
symbols = '$¢£¥€¤'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
print(codes)

[36, 162, 163, 165, 8364, 164]


In [2]:
#list comp
symbols = '$¢£¥€¤'
codes = [ord(symbol) for symbol in symbols]
print(codes)

[36, 162, 163, 165, 8364, 164]


In [3]:
# Variables assigned within the expression are local, but variables in the surrounding scope can still be referenced
x = "ABC"
dummy = [ord(x) for x in x]
print(x)

ABC


In [4]:
## listcomps versus filter

#list comp
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
print("listcomps:", beyond_ascii)

#using map and filter
beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))
print("map and filter:", beyond_ascii)

listcomps: [162, 163, 165, 8364, 164]
map and filter: [162, 163, 165, 8364, 164]


the speed was almost the same

In [5]:
%%time
symbols = '$¢£¥€¤'*10**7
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]

Wall time: 11.5 s


In [6]:
%%time
symbols = '$¢£¥€¤'*10**7
beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))

Wall time: 9.75 s


In [7]:
#Cartesian product using a list comprehension
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors 
                         for size in sizes]

In [8]:
#genexp
symbols = '$¢£¥€¤'
tuple(ord(symbol) for symbol in symbols)
import array
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [36, 162, 163, 165, 8364, 164])

## Tuples are not just immutable list (26p)

when using a tuple as a collection of fields, the number of items is often fixed and their order is always vital.

In [9]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

#Follwing is called "unpacking"
for country, _ in traveler_ids:
    print(country)


BRA/CE342567
ESP/XDA205856
USA/31195855
USA
BRA
ESP


In [10]:
#parallel assignment
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates

In [11]:
#Another example of tuple unpacking
t = (20, 8)
divmod(*t)
quotient, remainder = divmod(*t)

In [12]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [13]:
#Using * to grab excess items
a, b, *rest = range(5)
a, b, *rest = range(2)

In [14]:
metro_areas = [
('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]
print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0: 
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


### Named tuples (30p)

Instances of a class that you build with namedtuple take exactly the
same amount of memory as tuples because the field names are stored
in the class. They use less memory than a regular object because
they do store attributes in a per-instance __dict__.

In [15]:
import collections

In [16]:
Card = collections.namedtuple('Card', ['rank', 'suit'])

In [17]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [18]:
tokyo.population
tokyo.coordinates
tokyo[1]

'JP'

In [19]:
City._fields

('name', 'country', 'population', 'coordinates')

In [20]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data)
delhi._asdict()
for key, value in delhi._asdict().items():
    print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


## Slicing (33p)

### Slice objects

In [21]:
invoice = """
0.....6.................................40........52...55........
1909  Pimoroni PiBrella                     $17.50    3    $52.50
1489  6mm Tactile Switch x20                 $4.95    2     $9.90
1510  Panavise Jr. - PV-201                 $28.00    1    $28.00

1601  PiTFT Mini Kit 320x240                $34.95    1    $34.95
"""
SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)
line_items = invoice.split('\n')[2:]

In [22]:
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

    $17.50   Pimoroni PiBrella                 
     $4.95   6mm Tactile Switch x20            
    $28.00   Panavise Jr. - PV-201             
 
    $34.95   PiTFT Mini Kit 320x240            
 


### Multi-dimensional slicing and ellipsis (35p)

The ellipsis — written with three full stops ... and not … (Unicode U+2026) — is recognized
as a token by the Python parser. It is an alias to the Ellipsis object, the single
instance of the ellipsis class4. As such, it can be passed as an argument to functions
and as part of a slice specification, as in f(a, ..., z) or a[i:...]. NumPy uses ...
as a shortcut when slicing arrays of many dimensions, for example, if x is a 4-
dimensional array, x[i, ...] is a shortcut for x[i, :, :, :,]. See the Tentative
NumPy Tutorial to learn more about this.

### Assigning to slices

Mutable sequences can be grafted, excised and otherwise modified in-place using slice
notation on the left side of an assignment statement or as the target of a del statement.
The next few examples give an idea of the power of this notation.

In [23]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [25]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [26]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [27]:
l[2:5] = 100
l

TypeError: can only assign an iterable

### Using + and * with sequences (36p)

In [28]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [29]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [30]:
[[]] * 3

[[], [], []]

### Building lists of lists (37p)

In [31]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [32]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [33]:
#three references to the same inner list
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [34]:
weird_board[1][2] = 'O'
weird_board

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

### Augmented assignment with sequences (38p)

If a implements __iadd__, that will be called. In the case of mutable sequences like list,
bytearray, array.array, a will be changed in-place, i.e. the effect will be similar to
a.extend(b). However, when a does not implement __iadd__, the expression a += b
has the same effect as a = a + b: the expression a + b is evaluated first, producing a
new object which is then bound to a. In other words, the identity of the object bound
to a may or may not change, depending on the availability of __iadd__.

In [35]:
# id changed since it tuple can not be changed so assigned
a = (1)
print(id(a), a)
a += (2)
print(id(a), a)

140722693209632 1
140722693209696 3


In [36]:
# id not changed
a = [1]
print(id(a), a)
a += [2]
print(id(a), a)

2751249212296 [1]
2751249212296 [1, 2]


Repeated concatenation of immutable sequences is inefficient, because instead of just
appending new items, the interpreter has to copy the whole target sequence to create a
new one with the new items concatenated5

### A += assignment puzzler

In [37]:
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [38]:
t

(1, 2, [30, 40, 50, 60])

## list.sort and sorted built-in opeartion (42p)

An important Python API convention: functions or methods that change an object in-place should return __None__ to make it clear to the caller that the object itself was changed, and no new object was created.

The convention of returning __None__ to signal in-place changes has a drawback: you cannot cascade calls to those methods

In [39]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [40]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [41]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

Given a test score, grade returns the corresponding letter grade.

In [42]:
import bisect
import sys

def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

In [43]:
breakpoints=[60, 70, 80, 90]
score = 71
bisect.bisect_left(breakpoints, score)

2

Inserting with bisect.insort

In [44]:
import bisect
import random
SIZE = 7
random.seed(1729)
my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


## When a list is not the answer (47p)

The list type is flexible and easy to use, but depending on specific requirements there are better options. For example, if you need to store 10 million of floating point values an __array__ is much more efficient, because an __array__ does not actually hold full-fledged float objects, but only the packed bytes representing their machine values — just like an __array__ in the C language. On the other hand, if you are constantly adding and removing items from the ends of a list as a FIFO or LIFO data structure, a __deque__ (double-ended queue) works faster.

If your code does a lot of containment checks — e.g. item in my_col lection, consider using a __set__ for my_collection, especially if it holds a large number of items. Sets are optimized for fast membership checking. But they are not sequences (their content is unordered). We cover them in Chapter 3.

### array

If all you want to put in the list are numbers, an array.array is more efficient than a list: it supports all mutable sequence operations (including .pop, .insert and .extend), and additional methods for fast loading and saving such as .frombytes and .tofile.

In [45]:
from array import array
from random import random
floats = array('d', (random() for i in range(10**7))) #double precision floats
floats[-1]

0.5963321947530882

In [46]:
fp = open('floats.bin', 'wb')
floats.tofile(fp) # save the array to a binary file;
fp.close()
floats2 = array('d') # create an empty array of doubles;
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7) # read 10 million numbers from the binary file;
fp.close()
floats2[-1]

0.5963321947530882

In [47]:
floats2 == floats

True

That is nearly 60 times faster than reading the numbers from a text file, which also involves parsing each line with the float built-in.

Another fast and more flexible way of saving numeric data is the pickle module for object serialization. Saving an array of floats with
__pickle.dump__ is almost as fast as with __array.tofile__, but __pickle__ handles almost all built-in types, including complex numbers, nested collections and even instances of user defined classes automatically — if they are not too tricky in their implementation.

### compare to pickle and parquet

In [48]:
import pickle

In [49]:
%%time
floats = array('d', (random() for i in range(10**8))) #double precision floats
fp = open('floats.bin', 'wb')
floats.tofile(fp) # save the array to a binary file;
fp.close()

Wall time: 25.1 s


In [50]:
1+1

2

In [51]:
%%time
floats = array('d', (random() for i in range(10**8))) #double precision floats
with open('floats.pk', 'wb') as f:
    pickle.dump(floats, f)

Wall time: 27.6 s


## memoryview (51p)

*memorview* class is a shared-memory sequence type that lets you handle slices of arrays without copying bytes

When should a memory view be used?  
A memoryview is essentially a generalized NumPy array structure in Python itself (without the math). It allows you to share memory between data-structures (things like
PIL images, SQLlite databases, NumPy arrays, etc.) without first copying. This is very important for large data sets 

In [52]:
numbers = array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
print(numbers)

array('h', [-2, -1, 0, 1, 2])


In [53]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [54]:
print(numbers)

array('h', [-2, -1, 0, 1, 2])


## Numpy and Scipy

In [55]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
type(a)

numpy.ndarray

In [57]:
a.shape

(12,)

In [58]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
a[:,1]

array([1, 5, 9])

In [60]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [61]:
floats = np.array(np.load('floats.pk'))
#loadtxt method is used in the book but it doesnt work
#also the type of the object was array.array so chaneged the type into np array

In [62]:
floats[-3:]

array([0.38741937, 0.57363007, 0.85777082])

In [63]:
floats *= .5
floats[-3:]

array([0.19370968, 0.28681503, 0.42888541])

In [64]:
from time import perf_counter as pc

In [65]:
t0 = pc(); floats /= 3; pc() - t0

0.15296004300000732

In [ ]:
np.save('floats-10M', floats)

In [67]:
floats2 = np.load('floats-10M.npy', 'r+')

In [68]:
floats2 *= 6
floats2[-3:]

memmap([4.65204506, 2.31423189, 5.86856021])

## Deques and other queues

The class collections.deque is a thread-safe double-ended queue designed for fast inserting and removing from both ends

In [69]:
from collections import deque
dq = deque(range(10), maxlen=10)
print(id(dq))
dq

2751249209448


deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
dq.rotate(3)
print(id(dq)) #note that the id doesnt change
dq

2751249209448


deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [71]:
dq.appendleft(-1)
dq

deque([-1, 7, 8, 9, 0, 1, 2, 3, 4, 5])

In [72]:
dq.extendleft([10, 20, 30, 40])
dq
#note that extendleft(iter) works by appending each successive item of the iter argument to the left of the deque, 
#therefore the final position of the items is reversed.

deque([40, 30, 20, 10, -1, 7, 8, 9, 0, 1])

Besides deque, other Python Standard Library packages implement queues.  
queue, multiprocessing, asyncio, heapq

Further readings:  
how to sort: https://docs.python.org/3/howto/sorting.html  
Extended Iterable Unpacking: https://www.python.org/dev/peps/pep-3132/  
Why numbering should start at zero: https://www.cs.utexas.edu/users/EWD/transcriptions/EWD08xx/EWD831.html